SEED_USERS = [
    {
        "id": 1001,
        "username": "linqinghe",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "林清禾",
        "age": "23",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "工作日十点半前睡 / 周末会去深圳湾骑车 / 能接受稳定关系慢慢来",
        "bio": "工作节奏不算轻，所以会更珍惜下班后的时间。平时喜欢自己做点吃的、收拾房间、周末去海边吹风。希望认识一个说话温和、愿意认真投入关系的人，不用太会表达，但要稳定。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ["海边散步", "下班节奏", "认真恋爱"],
    },
    {
        "id": 1002,
        "username": "zhouyining",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "周以宁",
        "age": "24",
        "city": "深圳",
        "company": "字节跳动",
        "role": "算法工程师",
        "school": "华南理工大学",
        "tags": "周三固定打羽毛球 / 通勤路上听播客 / 不太喜欢反复试探",
        "bio": "工作里比较理性，生活里反而希望关系简单一点。喜欢有边界感、情绪稳定、愿意好好说话的人。比起热闹，我更在意相处时是不是轻松，能不能自然地聊到很晚。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ["播客", "羽毛球", "城市漫游"],
    },
    {
        "id": 1003,
        "username": "chenxingye",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "陈星野",
        "age": "25",
        "city": "深圳",
        "company": "美团",
        "role": "商业分析",
        "school": "暨南大学",
        "tags": "周末背相机乱走 / 路过花店会停一下 / 不玩突然消失",
        "bio": "朋友都说我看起来有点安静，但熟了以后其实挺爱说话。比起被人猛烈追求，我更喜欢那种相处里慢慢积累出来的喜欢。希望你有基本的分寸感，也有一点生活趣味。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ["摄影", "花店", "咖啡"],
    },
    {
        "id": 1004,
        "username": "xuwenxi",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "许闻溪",
        "age": "24",
        "city": "深圳",
        "company": "小红书",
        "role": "运营",
        "school": "深圳大学",
        "tags": "周末看展或探店 / 很少熬夜 / 喜欢有回应的人",
        "bio": "有点慢热，所以不太适合特别快节奏的关系。比较喜欢那种彼此都忙，但还是愿意留时间给对方的状态。对我来说，靠谱不只是准时和守约，也包括情绪上不让人猜来猜去。",
        "persona_type": "steady_listener",
        "reply_style": "慢热真诚",
        "opener_style": "warm_checkin",
        "active_window": "evening",
        "conversation_topics": ["看展", "探店", "规律生活"],
    },
    {
        "id": 1005,
        "username": "shenzhao",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "沈昭",
        "age": "23",
        "city": "深圳",
        "company": "华为",
        "role": "前端工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "下班后爱走路回家 / 拿铁少糖 / 聊天不喜欢端着",
        "bio": "不太喜欢把关系搞得很复杂。平时工作写代码已经够费脑子了，感情里就更希望舒服一点。想认识一个沟通正常、脾气不差、对未来有自己打算的人，最好也愿意一起把日子过具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "直接自然",
        "opener_style": "grounded_daily_life",
        "active_window": "night",
        "conversation_topics": ["散步", "咖啡", "工程师生活"],
    },
    {
        "id": 1006,
        "username": "seed1006",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "程雨桐",
        "age": "23",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1007,
        "username": "seed1007",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "梁知夏",
        "age": "24",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1008,
        "username": "seed1008",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "顾念之",
        "age": "25",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1009,
        "username": "seed1009",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "何清妍",
        "age": "26",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1010,
        "username": "seed1010",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "宋晚晴",
        "age": "27",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1011,
        "username": "seed1011",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "姜书意",
        "age": "28",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1012,
        "username": "seed1012",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "唐可心",
        "age": "23",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1013,
        "username": "seed1013",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "陆安然",
        "age": "24",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1014,
        "username": "seed1014",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "韩予宁",
        "age": "25",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1015,
        "username": "seed1015",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "苏念初",
        "age": "26",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1016,
        "username": "seed1016",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "沈知微",
        "age": "27",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1017,
        "username": "seed1017",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "温见月",
        "age": "28",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1018,
        "username": "seed1018",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "许嘉宁",
        "age": "23",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1019,
        "username": "seed1019",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "乔以安",
        "age": "24",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1020,
        "username": "seed1020",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "周书瑶",
        "age": "25",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1021,
        "username": "seed1021",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "林若岚",
        "age": "26",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1022,
        "username": "seed1022",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "陈予安",
        "age": "27",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1023,
        "username": "seed1023",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "谢听澜",
        "age": "28",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1024,
        "username": "seed1024",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "袁可宁",
        "age": "23",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1025,
        "username": "seed1025",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "黎映秋",
        "age": "24",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1026,
        "username": "seed1026",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "程雨桐",
        "age": "25",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1027,
        "username": "seed1027",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "梁知夏",
        "age": "26",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1028,
        "username": "seed1028",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "顾念之",
        "age": "27",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1029,
        "username": "seed1029",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "何清妍",
        "age": "28",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1030,
        "username": "seed1030",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "宋晚晴",
        "age": "23",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1031,
        "username": "seed1031",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "姜书意",
        "age": "24",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1032,
        "username": "seed1032",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "唐可心",
        "age": "25",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1033,
        "username": "seed1033",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "陆安然",
        "age": "26",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1034,
        "username": "seed1034",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "韩予宁",
        "age": "27",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1035,
        "username": "seed1035",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "苏念初",
        "age": "28",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1036,
        "username": "seed1036",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "沈知微",
        "age": "23",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1037,
        "username": "seed1037",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "温见月",
        "age": "24",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1038,
        "username": "seed1038",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "许嘉宁",
        "age": "25",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1039,
        "username": "seed1039",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "乔以安",
        "age": "26",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1040,
        "username": "seed1040",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "周书瑶",
        "age": "27",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1041,
        "username": "seed1041",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "林若岚",
        "age": "28",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1042,
        "username": "seed1042",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "陈予安",
        "age": "23",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1043,
        "username": "seed1043",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "谢听澜",
        "age": "24",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1044,
        "username": "seed1044",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "袁可宁",
        "age": "25",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1045,
        "username": "seed1045",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "黎映秋",
        "age": "26",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1046,
        "username": "seed1046",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "程雨桐",
        "age": "27",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1047,
        "username": "seed1047",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "梁知夏",
        "age": "28",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1048,
        "username": "seed1048",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "顾念之",
        "age": "23",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1049,
        "username": "seed1049",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "何清妍",
        "age": "24",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1050,
        "username": "seed1050",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "宋晚晴",
        "age": "25",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1051,
        "username": "seed1051",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "姜书意",
        "age": "26",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1052,
        "username": "seed1052",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "唐可心",
        "age": "27",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1053,
        "username": "seed1053",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "陆安然",
        "age": "28",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1054,
        "username": "seed1054",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "韩予宁",
        "age": "23",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1055,
        "username": "seed1055",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "苏念初",
        "age": "24",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1056,
        "username": "seed1056",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "沈知微",
        "age": "25",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1057,
        "username": "seed1057",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "温见月",
        "age": "26",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1058,
        "username": "seed1058",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "许嘉宁",
        "age": "27",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1059,
        "username": "seed1059",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "乔以安",
        "age": "28",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1060,
        "username": "seed1060",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "周书瑶",
        "age": "23",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1061,
        "username": "seed1061",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "林若岚",
        "age": "24",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1062,
        "username": "seed1062",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "陈予安",
        "age": "25",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1063,
        "username": "seed1063",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "谢听澜",
        "age": "26",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1064,
        "username": "seed1064",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "袁可宁",
        "age": "27",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1065,
        "username": "seed1065",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "黎映秋",
        "age": "28",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1066,
        "username": "seed1066",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "程雨桐",
        "age": "23",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1067,
        "username": "seed1067",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "梁知夏",
        "age": "24",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1068,
        "username": "seed1068",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "顾念之",
        "age": "25",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1069,
        "username": "seed1069",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "何清妍",
        "age": "26",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1070,
        "username": "seed1070",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "宋晚晴",
        "age": "27",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1071,
        "username": "seed1071",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "姜书意",
        "age": "28",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1072,
        "username": "seed1072",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "唐可心",
        "age": "23",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1073,
        "username": "seed1073",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "陆安然",
        "age": "24",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1074,
        "username": "seed1074",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "韩予宁",
        "age": "25",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1075,
        "username": "seed1075",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "苏念初",
        "age": "26",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1076,
        "username": "seed1076",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "沈知微",
        "age": "27",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1077,
        "username": "seed1077",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "温见月",
        "age": "28",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1078,
        "username": "seed1078",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "许嘉宁",
        "age": "23",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1079,
        "username": "seed1079",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "乔以安",
        "age": "24",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1080,
        "username": "seed1080",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "周书瑶",
        "age": "25",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1081,
        "username": "seed1081",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "林若岚",
        "age": "26",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1082,
        "username": "seed1082",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "陈予安",
        "age": "27",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1083,
        "username": "seed1083",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "谢听澜",
        "age": "28",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1084,
        "username": "seed1084",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "袁可宁",
        "age": "23",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1085,
        "username": "seed1085",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "黎映秋",
        "age": "24",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1086,
        "username": "seed1086",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "程雨桐",
        "age": "25",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1087,
        "username": "seed1087",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "梁知夏",
        "age": "26",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1088,
        "username": "seed1088",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "顾念之",
        "age": "27",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1089,
        "username": "seed1089",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "何清妍",
        "age": "28",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1090,
        "username": "seed1090",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "宋晚晴",
        "age": "23",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1091,
        "username": "seed1091",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "姜书意",
        "age": "24",
        "city": "深圳",
        "company": "大疆",
        "role": "后端工程师",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1092,
        "username": "seed1092",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "唐可心",
        "age": "25",
        "city": "深圳",
        "company": "招商银行",
        "role": "数据分析师",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1093,
        "username": "seed1093",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "陆安然",
        "age": "26",
        "city": "深圳",
        "company": "OPPO",
        "role": "算法工程师",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1094,
        "username": "seed1094",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "韩予宁",
        "age": "27",
        "city": "深圳",
        "company": "vivo",
        "role": "前端工程师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1095,
        "username": "seed1095",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "苏念初",
        "age": "28",
        "city": "深圳",
        "company": "Shopee",
        "role": "用户研究员",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1096,
        "username": "seed1096",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
        "name": "沈知微",
        "age": "23",
        "city": "深圳",
        "company": "腾讯",
        "role": "产品经理",
        "school": "中山大学",
        "tags": "周末喜欢逛菜市场 / 会认真回消息 / 不擅长冷战",
        "bio": "我不算特别外向，不过熟了以后其实挺会分享生活。比起热闹，我更喜欢两个人把平常日子过得具体。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1097,
        "username": "seed1097",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
        "name": "温见月",
        "age": "24",
        "city": "深圳",
        "company": "字节跳动",
        "role": "运营",
        "school": "暨南大学",
        "tags": "下班后会去散步 / 喜欢小馆子 / 关系里看重稳定",
        "bio": "喜欢稳定和真诚，不太擅长和人拉扯。希望你也愿意认真认识一个人，而不是只图一时新鲜。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    },
    {
        "id": 1098,
        "username": "seed1098",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        "name": "许嘉宁",
        "age": "25",
        "city": "深圳",
        "company": "美团",
        "role": "品牌策划",
        "school": "哈尔滨工业大学（深圳）",
        "tags": "周末看展 / 爱喝手冲 / 不喜欢过度试探",
        "bio": "平时会给自己留一点发呆和散步的时间，也期待身边的人有自己的节奏。相处舒服对我来说真的很重要。",
        "persona_type": "warm_flirt",
        "reply_style": "轻松有来回",
        "opener_style": "soft_flirty",
        "active_window": "evening",
        "conversation_topics": ['咖啡', '周末计划', '见面氛围'],
    },
    {
        "id": 1099,
        "username": "seed1099",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
        "name": "乔以安",
        "age": "26",
        "city": "深圳",
        "company": "小红书",
        "role": "设计师",
        "school": "北京师范大学珠海",
        "tags": "会打羽毛球 / 喜欢播客 / 情绪来得快去得也快",
        "bio": "比起特别会说的人，我更容易被靠谱和温柔打动。希望认识一个能正常沟通、情绪稳定的人。",
        "persona_type": "steady_listener",
        "reply_style": "温和认真",
        "opener_style": "daily_life",
        "active_window": "evening",
        "conversation_topics": ['散步', '认真恋爱', '日常节奏'],
    },
    {
        "id": 1100,
        "username": "seed1100",
        "gender": "female",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        "name": "周书瑶",
        "age": "27",
        "city": "深圳",
        "company": "华为",
        "role": "商业分析",
        "school": "武汉大学",
        "tags": "喜欢 citywalk / 爱买花 / 认真对待每次见面",
        "bio": "工作日会忙，但我一直觉得关系要靠持续表达来维系。希望认识一个沟通顺畅、说话有分寸感的人。",
        "persona_type": "thoughtful_analyst",
        "reply_style": "理性慢热",
        "opener_style": "curious_question",
        "active_window": "night",
        "conversation_topics": ['播客', '工作状态', '城市生活'],
    }
]

STARTER_MESSAGES = {
    1001: [
        "看到你也在深圳，平时会去海边散步吗？",
        "我一般周末傍晚会去深圳湾走一圈。",
    ],
    1003: [
        "你资料里的那句自我介绍挺真诚的。",
        "感觉可以先从一杯咖啡开始认识。",
    ],
}

REPLY_TEMPLATES = {
    "steady_listener": {
        "greeting": [
            "嗨，我刚下班，看到你的消息了。",
            "你好呀，你开场比很多人自然。",
        ],
        "work_school": [
            "我平时工作节奏不算慢，不过会尽量把下班后的时间留给自己喜欢的人和事。",
            "学校那几年让我养成了比较稳定的生活节奏，所以现在也还是很看重相处是不是舒服。",
        ],
        "interest": [
            "我最近最常做的还是去海边走走，脑子会安静很多。",
            "周末如果天气好，我一般会出门走走或者找个安静的地方坐一会儿。",
        ],
        "compliment": [
            "你这样说会让我更想继续聊下去。",
            "谢谢你认真看我的资料，这点其实挺加分的。",
        ],
        "invite": [
            "如果再多聊几句感觉对，我会愿意一起喝杯咖啡。",
            "我不排斥见面，不过会更喜欢先聊到彼此都放松一点。",
        ],
        "generic": [
            "这个话题我能接住，你平时也会这样想吗？",
            "你继续说，我想看看你平时是怎么理解这件事的。",
        ],
    },
    "thoughtful_analyst": {
        "greeting": [
            "你好，我刚忙完一阵，看到你的消息了。",
            "嗨，你这个开场还挺自然的。",
        ],
        "work_school": [
            "我现在的工作会比较偏理性一点，所以我反而很珍惜跟人好好聊天的时刻。",
            "学校和工作都让我变得有点慢热，但熟了之后其实很好聊。",
        ],
        "interest": [
            "我最近会把很多注意力放在播客、散步和一点点运动上。",
            "如果是放松一点的兴趣，我比较常去打球或者找个地方慢慢走。",
        ],
        "compliment": [
            "你这句话会让我觉得你挺会观察人的。",
            "这种表达方式我会有好感，不会太冒进。",
        ],
        "invite": [
            "见面我不排斥，但我会更喜欢先把话聊顺一点。",
            "如果聊天感觉稳定，我会愿意把咖啡排进周末计划。",
        ],
        "generic": [
            "这个角度还挺有意思的，你是一直都这么想吗？",
            "我会比较想知道你为什么会这么说。",
        ],
    },
    "warm_flirt": {
        "greeting": [
            "你好呀，这句开场还挺让我愿意回的。",
            "嗨，看到你的消息时我刚好在摸鱼喝咖啡。",
        ],
        "work_school": [
            "我工作里会比较认真，但聊天的时候更喜欢轻松一点。",
            "学校和工作都让我认识了很多人，所以我现在更看重相处有没有火花。",
        ],
        "interest": [
            "我最近最常做的是背着相机乱走，顺便给好看的店门口停一下。",
            "如果是周末，我多半会在咖啡店、展览或者街上乱逛。",
        ],
        "compliment": [
            "你这么说，我会有点想继续逗你两句。",
            "这句挺会说的，我先记你一分。",
        ],
        "invite": [
            "如果你线下也跟现在一样自然，我会愿意见面。",
            "喝咖啡可以呀，但你得负责把开场继续撑住。",
        ],
        "generic": [
            "这个话题我能聊，你再往下说说看。",
            "我觉得你应该还有后半句，别停在这。",
        ],
    },
}
